# Generated by Django 2.2.12 on 2020-04-20 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(db_index=True, max_length=15, null=True, unique=True),
        ),
    ]
