# Generated by Django 2.2.12 on 2020-04-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorting', '0002_auto_20200420_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_url',
            field=models.CharField(blank=True, db_index=True, max_length=15, unique=True),
        ),
    ]
