# Generated by Django 2.2.12 on 2020-05-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorting', '0004_auto_20200516_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='url',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
