# Generated by Django 2.2.12 on 2020-06-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorting', '0005_auto_20200516_1755'),
    ]

    operations = [        
        migrations.AddField(
            model_name='link',
            name='time_called',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
